### ISSUE TITLE
In IOS, when keyboard is open toast message was coming under keyboard

### ISSUE THREAD

**Issue by Satish-Eruvaka** [ponnamkarthik/FlutterToast#147]

**Comment by achinverma** [comment]
i am getting the same, any solutions for this?

**Comment by martinellimarco** [comment]
I am experiencing this problem too on iOS. Is there anything I can do to fix this? For now I'm forcing the keyboard to close but it's not optimal.

**Comment by achinverma** [comment]
> I am experiencing this problem too on iOS. Is there anything I can do to fix this? For now I'm forcing the keyboard to close but it's not optimal.

Hi, you change the Toast Gravity to Top or Center.

**Comment by faiyyazs** [comment]
Have recently created a PR for the above issues. #203 for IOS. 

Until reviewed & merged you can check my fork
```
fluttertoast:
    git:
      url: https://github.com/faiyyazs/FlutterToast.git
      ref: master
```
Thanks.
