### ISSUE TITLE
MissingPluginException('No implementation found for method $method on channel $name');

### ISSUE THREAD

**Issue by PaworD** [PonnamKarthik/FlutterToast#175]
Hello there, n recent days I have been working with flutter project. After adding one new packeage to pubspec.yaml the following error appears and debug mode does not start:

```
/C:/Users/User/flutter/packages/flutter/lib/src/services/platform_channel.dart:154:7: Error: Expected an identifier, but got ','.
      ,throw MissingPluginException('No implementation found for method $method on channel $name');
      ^
/C:/Users/User/flutter/packages/flutter/lib/src/services/platform_channel.dart:154:7: Error: Expected ';' after this.
      ,throw MissingPluginException('No implementation found for method $method on channel $name');
      ^
/C:/Users/User/flutter/packages/flutter/lib/src/services/platform_channel.dart:154:7: Error: Unexpected token ','.
      ,throw MissingPluginException('No implementation found for method $method on channel $name');
      ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 2s
Gradle task assembleDebug failed with exit code 1
```

Here is my pubspec.yaml:

```
environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  badges: ^1.0.0
  provider: 3.0.0
  intl: ^0.16.1 
  http: ^0.12.0+4
  shared_preferences: ^0.5.6+2
  flutter_clean_calendar: ^1.0.2+1
  url_launcher: ^5.4.10
```

Also I tried 

``` flutter clean ```
``` flutter get ```

But it did not help.
