### ISSUE TITLE
Toast message works on simulator but not on real Android device

### ISSUE THREAD

**Issue by marcoprado17** [ponnamkarthik/FlutterToast#210]
For some reasoson, the toast message works on Android emulator, but not on a real device.

On the emulator it works:

![Screenshot_84](https://user-images.githubusercontent.com/4203657/89980098-92afb980-dc47-11ea-9a69-5a06cf37c134.png)

![Screenshot_87](https://user-images.githubusercontent.com/4203657/89980114-96dbd700-dc47-11ea-8b05-affd28858b07.png)

![Screenshot_86](https://user-images.githubusercontent.com/4203657/89980117-980d0400-dc47-11ea-9dc0-a7e7254852e3.png)

But not in a real device (Android 9), what I am missing???

![WhatsApp Image 2020-08-12 at 02 58 50](https://user-images.githubusercontent.com/4203657/89980946-4c5b5a00-dc49-11ea-9346-98440d9f4d50.jpeg)

It shows a gray box in the place of the customized toast message.

Follow the code I am using:

pubspec.yaml

```yaml
# ...
dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.0-dev.6
  freezed_annotation: ^0.11.0+1
  uuid: ^2.0.4
  flutter_bloc: ^6.0.1
  auto_route: ^0.6.7
  get_it: ^4.0.4
  meta: ^1.1.8
  firebase_core: ^0.4.3+3
  firebase_auth: ^0.16.1
  google_sign_in: ^4.1.1
  cloud_firestore: ^0.13.3
  firebase_crashlytics: ^0.1.4+1
  injectable: ^1.0.4
  json_annotation: ^3.0.1
  validators: ^2.0.1
  flutter_spinkit: "^4.1.2"
  fluttertoast: ^7.0.2
# ...
```

I am calling the lib from a static method passing the widget context

```dart
import 'package:flutter/material.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:vacina_delivery_v1/style/style_constants.dart';

class ToastMessage {
  static showError(BuildContext context, String message) {
    var fToast = FToast(context);
    
    Widget toast = Container(
      padding: const EdgeInsets.symmetric(
        horizontal: StyleConstants.TOAST_MESSAGE_HORIZONTAL_PADDING, 
        vertical: StyleConstants.TOAST_MESSAGE_VERTICAL_PADDING
      ),
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(StyleConstants.TOAST_MESSAGE_BORDER_RADIUS),
        color: StyleConstants.TOAST_MESSAGE_ERROR_COLOR,
      ),
      child: Expanded(
        child: Text(
          message,
        )
      )
    );

    fToast.showToast(
        child: toast,
        gravity: ToastGravity.BOTTOM,
        toastDuration: Duration(seconds: 2),
    );
  }
}
```

Thanks for the support, 

Marco
