### ISSUE TITLE
Background color does not fill the whole Toast (ver 2.1.0)

### ISSUE THREAD

**Issue by jkyeo** [PonnamKarthik/FlutterToast#29]
As shown below, Background color does not fill the whole Toast.
<img width="390" alt="image" src="https://user-images.githubusercontent.com/4645158/48400856-7de87e00-e762-11e8-8c11-b1a4a19c7001.png">

---

ENV:

```
Google Pixel 2 XL running Android 9
```

```
fluttertoast:
    dependency: "direct main"
    description:
      name: fluttertoast
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.11.3, on Mac OS X 10.14.1 18B75, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.28.2)
[✓] Connected device (3 available)

• No issues found!
```
